name: Update ACLED Data

on:
  # Manual trigger from GitHub UI (no inputs)
  workflow_dispatch:
  
  # Automatic trigger every Tuesday at 1am EST (which is 5am UTC)
  schedule:
    - cron: '0 5 * * 2'

jobs:
  update-acled-data:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Install any dependencies if needed
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Run your update script and capture exit code
      - name: Run ACLED data update script
        id: update_script
        env:
          ACLED_API_KEY: ${{ secrets.ACLED_API_KEY }}
          ACLED_EMAIL: ${{ secrets.ACLED_EMAIL }}
        run: |
          python scripts/update-acled-data.py
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Build Svelte app
        run: |
          npm install
          npm run build

      # Commit and push any changes made by the script if exit code is 0
      - name: Commit and push changes
        if: steps.update_script.outputs.exit_code == '0'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "GH-Bot: Update ACLED data - $(date +'%Y-%m-%d')"
          git push
