name: Update ACLED Data

on:
  # Manual trigger from GitHub UI (no inputs)
  workflow_dispatch:
  
  # Automatic trigger every Tuesday at 1am EST (which is 5am UTC)
  schedule:
    - cron: '0 5 * * 2'

jobs:
  update-acled-data:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # Install any dependencies if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt file:
          # pip install -r requirements.txt
          # Or install specific packages:
          # pip install pandas requests
      
      # Run your update script
      - name: Run ACLED data update script
        run: python scripts/update-acled-data.py
          
      # Commit and push any changes made by the script
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update ACLED data - $(date +'%Y-%m-%d')"
          git push
